### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by RobinFrugte97** [stanRepo/web-app-from-scratch-2021#11]
Yo Stan!

Wat je readme betreft, ziet er goed uit! Alleen je screenshots werken volgens mij niet helemaal..

Kijk eens of je wat meer structuur kan aanbrengen in je mappen. Nu staat alles in één map `projects`. We hebben het er vanmorgen al over gehad, maar wat je op z'n minst kan doen is de javascript in een js map zetten en je css in een css map.
Je js modules kan je dan in een map `modules` zetten binnen de js map. Dit maakt je mappen structuur leesbaar. Kijk of je je templates ook op en logische plek kan zetten. Het is een beetje lastig om je structuur te volgen.

Bijvoorbeeld:
```
- js
   - modules(met al je modules erin)
   - app.js
- css
   - styles.css
- index.html
```
Misschien kun je je modules weer verder opdelen, zoals we vanmorgen besproken hadden. Je hebt nu je modules die constante zijn en modules die je daadwerkelijk uitvoert door elkaar heen staan. Ook staan je templates door je js heen. Denk dat je het wel snapt, kijk maar. Wel op je imports letten als je de mappenstructuur aanpast!

Over je code zelf: Heel netjes. Mooi gestructureerd. Je doet het op een hele andere manier dan verwacht van cmd studenten, maar wel heel nice. Geslaagde refactor!

Als je specifiek ergens feedback op wilt moet je dat even laten weten!

Ga zo door man

**Comment by stanRepo** [comment]
Hey Robin bedankt voor je review,

- [x] er is inderdaad iets met de links van de afbeeldingen... wordt aan gewerkt. Ze zijn alsnog in te zien via de /assets folder
- [x] Heb ondertussen het een en ander in aparte folders gezet. Ik ga zeker de files die alleen constante bevatten scheiden van de rest.

Ik ga hiermee aan de slag!
