### ISSUE TITLE
URL privacy netlify

### ISSUE THREAD

**Issue by suustenvoorde** [stanRepo/web-app-from-scratch-2021#13]
I think there is something with your www record, see the difference:
[https://www.wafs2021.netlify.com/](https://www.wafs2021.netlify.com/)
[https://wafs2021.netlify.app/](https://wafs2021.netlify.app/)

**Comment by stanRepo** [comment]
Hi there,
thnx for looking into my repo!

I've looked into this. 

It seems when the site is visited with the url: [ .app ] (wafs2021.netlify.app) that the problem isn't showing. So I've changed the url in the about section to this one. I don't think this is the best solution but it definitly seems to fix it for now.
