### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by NathanNeelis** [stanRepo/web-app-from-scratch-2021#2]
### Repository
❌  there a repo description at the top? --> Dit is de descriptie van je geforkte repo, deze is nog hetzelfde.
✅  Is the repo open to issues?
✅  Does it include a gitignore
✅ Is the concept described well in the readme?
❌  Is the API described in the readme? --> Wel genoemd, niet beschreven.

#### Check the code against our course's best practices
Tips:
* Het is best wel lastig om je code van A tot Z door te lezen. Ik snap dat je vroeg bent begonnen met modules, maar op dit moment is het lastig om te zien waar je 'main' code begint en in welke volgorde ik dit zou moeten lezen.
* Mogelijk helpt het ook om meer code-comments toe te voegen, die mij vertellen wat elk stukje code doet.
Je schrijft je code op een totaal andere manier dan ik zelf codeer, en ik vind het lastig om het te volgen op deze manier. Uitleg zou me waarschijnlijk een stuk verder helpen.
* Niet om te zeggen dat je het op een andere manier doet, maar je gaf aan dat ik vooral moest laten zien hoe ik het zou doen. Hieronder een klein stukje code voorbeeld hoe ik codeer. Ik gebruik meer functional programming.
```Javascript

makeContent()
async function makeContent() {
    getData(url, key, language, sort, page)
        .then(data => {

            // function(s) to transform data  
            let resultsPageOne = data.results;
            let cleanObject = filterObject(resultsPageOne)
            // let topTwentyTitles = filterData(cleanObject, 'title')
            // let topTwentyImages = filterData(cleanObject, 'poster_path')


            // console logs
            console.log('Incoming data', data)
            console.log('results page 1', resultsPageOne)
            console.log('new object', cleanObject)


            // function(s) to render data
            arrayToHtml(cleanObject)

        });
}

```
Hierboven is dus de grote function die alle content ophaald en verwerkt. In deze function roep ik andere functions aan die het werk doen. Je ziet bijvoorbeeld dat ik de funcie `getData()` gebruik om me data op te halen. Die heb ik eronder gedefineerd.

```Javascript
async function getData(url, key, language, sort, page) {
    const response = await fetch(url + key + language + sort + page);
    const data = await response.json();
    return data;
}

```

Ook filter ik mijn object, aangezien er veel informatie in zit die ik niet gebruik. Dit doe ik weer met een buitenstaande functie, die ik in de hoofdfunctie aanroep. Namelijk `filterObject`. Deze heb ik hieronder nog even weergeven.

```Javascript
// creates a new object with the data I want, so I dont have to much data that I wont be using
function filterObject(results) {
    let items = results.map((results) => {
        return {
            title: results.title,
            poster_path: results.poster_path,
            vote_average: results.vote_average,
            overview: results.overview
        }
    });

    return items
}
```

Tops: 
* Je zet goed je variablen boven neer, zo kan ik goed wat bijvoorbeeld de endpoints zijn.

#### Check the code for consistency, is code being written the same way in different places?
Tops: 
* ziet er goed uit. Je concistency is duidelijk. Overal ES6 functions aan variabelen. 

#### Does the code follow naming conventions? Do variable and function names make sense to you?
Tips: 
* Zou je nog even goed naar moeten kijken. Sommige functies zijn niet altijd even duidelijk. Bijvoorbeeld: `const events` hier weet ik niet gelijk van wat deze functie gaat doen.

**Comment by stanRepo** [comment]
Bedankt voor je review.

Ik begrijp je tips. De manier hoe ik het schrijf schept bij mij ook verwarring zo nu en dan. 
Ik wil nog diagrammen toevoegen en refactoren. Dat zou al voor veel meer duidelijkheid moeten zorgen....

ps. de README.md zat in een subdirectory;)

**Comment by NathanNeelis** [comment]
Ja dat had ik gezien. 
Maar de Repo description staat alleen in de hoofd repo. 
Zie afbeelding

![Schermafbeelding 2021-02-05 om 11 44 33](https://user-images.githubusercontent.com/55492381/107023906-9318af80-67a7-11eb-83d2-2c186f5eef6f.png)

**Comment by stanRepo** [comment]
Thnx voor de review:
- [X] Readme is nu op top-level
- [X] API wordt nu ook beschreven
- [X] Aan de naming convention is volop gewerkt!
