### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by jonahgoldwastaken** [stanRepo/web-app-from-scratch-2021#5]
# Peer review 2

Je code is echt heel netjes man. Je mag je zeker hoger inschatten dan dat je zelf doet. Ik zie niet veel mensen even een volledige OOP app schrijven. Hierbij nog wel wat feedback, wat voornamelijk kleine dingetjes zijn.

## Repository

- [ ] Actor diagram mist
- [ ] Interaction diagram mist
- [ ] App werkt op dit moment niet, maar het wordt gerefactord dus dat komt goed
- [ ] Beschrijving van de API mist nog, en hoe die opgezet kan worden

## Code

- [ ] Code is atm kapot, dus kan de demo niet beoordelen
- [ ] Classes beginnen altijd met een hoofdletter in JS, dat is een conventie. Atm verschilt het best veel hoe je de namen opbouwt.
- [ ] Zet je methods buiten de class constructors, die hoeven niet daarin te staan. Die zet je gebruikelijk onder de constructor, zonder `this.` ervoor.
- [ ] Kijk heel goed naar hoe je je classes wilt extenden. Je gebruikt namelijk lang niet alle methods die je definieert, maar wel overneemt. Je classes worden hierdoor heel erg bloated. Kijk hoe je je classes met elkaar kan laten communiceren, zonder dat je ze `extend`.
- [ ] Kijk welke array methods je kan gebruiken (`.forEach`, `.map`, `.reduce`, etc.) om je code compacter te maken.
- [ ] Je maakt vaak variabelen aan die precies dezelfde waarde hebben als de parameter die je meegeeft. Geef de parameter dan een naam die voor jou logisch is, dit bespaart onnodige regels code.

## Store class

- [ ] Maak van this.state een object dat de state bevat
- [ ] Zet de methods (stateDelete etc) in de class zelf, buiten de constructor, en laat die this.state aanroepen.
- [ ] De constructor populate this.state met een object dat uit localStorage wordt gehaald, en wanneer this.state wordt aangepast schrijf je dat weer naar localstorage. Kijk naar [setters](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) en [getters](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get). Met deze dingen kan je dus bepalen wat er gebeurt als een waarde op this.state wordt gezet en wat er gebeurt als je de waarde ophaalt. Ik gebruik zoiets als dit ook met [mijn state functie](https://github.com/theonejonahgold/web-app-from-scratch-2021/blob/f0dfa01b0db9c15fa9e45a7157e91d069cc04df2/scripts/utils/state.js#L11). Jij hoeft dit niet te doen hoe ik het doe, maar je zet gewoon `get` of `set` voor de naam van je class property, zoals in die setters en getters linkjes gebeurt.

**Comment by stanRepo** [comment]
- [X] Actor Diagram is toegevoegd
- [X] Interaction Diagram is toegevoegd
- [X] App werkt op dit moment naar behoren!
- [X] API is nu beschreven in de README.md
- [X] Classes beginnen nu met een hoofdletter
- [ ] Classes zijn wellicht nog steeds "bloated". Ik neem dit mee in mijn procesverslag
- [X] Array methods zijn toegevoegd
- [X] parameters hebben nu een meer passende naamgeving
- [X] `this.state` is nu `Class Store`. Wordt op verschillende plekken aangeroepen met `this.store = new Store`
- [X] methods zitten nu in de `Class`
- [ ] Getters & setters wil ik mij nog verder in verdiepen. Ik hoop dit nog te kunnen verwerken deze periode
