### ISSUE TITLE
Create different folders for you CSS/JS

### ISSUE THREAD

**Issue by suustenvoorde** [stanRepo/web-app-from-scratch-2021#7]
You stored everything in the project folder, I should advise to separate your CSS and JS in different files. And maybe a module file for your modules. Something like this:

- index.html
- CSS
- SCRIPTS 

And scripts folder:
- app.js
- modules folder

**Comment by stanRepo** [comment]
Thnx for the Review!!

- [X] I created the following directories:  /modules, /html and /css. I added the corrosponding files to the directories.
