### ISSUE TITLE
Is routie a module? I would suggest to store it in a folder called vendor

### ISSUE THREAD

**Issue by suustenvoorde** [stanRepo/web-app-from-scratch-2021#8]
https://github.com/stanRepo/web-app-from-scratch-2021/blob/99cec0002f183df343c73bdae08096904ccac9e2/project/index.html#L102

"The vendor folder is where you usually (I'm using the word 'usually' because it's not exactly a rule but more of a preference in the coding community with the purpose of having a semantic directory structure) keep third-party resources(icons, images, codes, you name it)"

bron: [stackoverflow](https://stackoverflow.com/questions/50052846/use-of-vendor-folder-in-web-design)

**Comment by stanRepo** [comment]
Thnx for the review

- [X] I've added a /vendor/scripts directory which now includes routie.js
